import { useState } from 'react';
import { ArrowRight, MessageCircle, Send, X } from 'lucide-react';
import { useApp } from './context';
import { listEntities } from './store';
import { platform } from './platform';
import { availableModels, modelFromProvider, modelLabel, pickModel, workContext } from './ai';

function DrawerShell({ title, icon, onClose, children }: { title:string; icon:React.ReactNode; onClose():void; children:React.ReactNode }) {
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><span>{icon}<strong>{title}</strong></span><button className="icon-button" onClick={onClose}><X size={18}/></button></div>{children}</aside></div>;
}

export function AssistantDrawer({ initialPrompt, onClose }: { initialPrompt:string; onClose():void }) {
  const app=useApp(); const [input,setInput]=useState(initialPrompt); const [busy,setBusy]=useState(false); const [messages,setMessages]=useState<Array<{role:'user'|'assistant';text:string}>>([]);
  const providers=availableModels(app.state.entities);const [providerId,setProviderId]=useState('');const provider=providers.find(p=>p.id===providerId)??pickModel(app.state.entities,'面宝');const loadedSkills=listEntities(app.state,{kind:'skill'}).filter(s=>s.meta.loadedForMianbao);const memories=listEntities(app.state,{kind:'memory'}).filter(m=>!m.workId);const chatHistory=listEntities(app.state,{kind:'chat'}).filter(c=>c.category==='助手');
  const send=async()=>{const message=input.trim();if(!message)return;if(app.state.preferences.memoryLearning!==false&&/^记住[：:]/.test(message)){app.add('memory','面宝学习记忆',message.replace(/^记住[：:]\s*/,''),{category:'learned'});app.notify('已加入面宝可编辑记忆');}setInput('');setMessages(xs=>[...xs,{role:'user',text:message}]);const model=modelFromProvider(provider);if(!model){app.notify('先在 AI 配置中添加模型');return;}setBusy(true);try{const text=await platform().runAi({...model,prompt:`你是 JZRM 创作助手。结合当前作品资料，回答问题；如需进入功能页，明确说出功能名称。不要虚构尚未提供的事实。\n装载技能：\n${loadedSkills.map(s=>`${s.title}：${s.content}`).join('\n').slice(0,10000)}\n长期偏好与规则：\n${memories.map(m=>`${m.title}：${m.content}`).join('\n').slice(0,8000)}\n作品资料：\n${workContext(app.state.entities,app.workId,app.state.preferences.contextLimit)}\n对话：\n${messages.slice(-8).map(m=>`${m.role}:${m.text}`).join('\n')}\nuser:${message}`});setMessages(xs=>[...xs,{role:'assistant',text}]);app.add('chat','助手会话',`${message}\n\n${text}`,{workId:app.workId,category:'助手'});}catch(e){app.notify(String(e));}finally{setBusy(false);}};
  const quick=[['去写正文',app.workId?`/work/${app.workId}/body`:'/library'],['打开设定',app.workId?`/work/${app.workId}/settings`:'/library'],['审查修改','/review'],['剧本杀改编','/adaptation'],['作品拆解','/split']];
  return <DrawerShell title="助手" icon={<MessageCircle size={19}/>} onClose={onClose}><div className="drawer-subhead">围绕当前作品对话，也可直接启用并跳转功能页。</div><div className="quick-links">{quick.map(([label,path])=><button key={label} onClick={()=>{app.navigate(path);onClose();}}>{label}<ArrowRight size={14}/></button>)}</div><div className="assistant-history"><select aria-label="历史助手会话" defaultValue="" onChange={e=>{const entry=chatHistory.find(c=>c.id===e.target.value);if(entry)setMessages([{role:'assistant',text:entry.content}]);}}><option value="">历史会话（{chatHistory.length}）</option>{chatHistory.map(c=><option key={c.id} value={c.id}>{c.title} · {new Date(c.createdAt).toLocaleString()}</option>)}</select><button className="button" onClick={()=>setMessages([])}>新会话</button></div><div className="chat-feed">{messages.length?messages.map((m,i)=><div key={i} className={`chat-bubble ${m.role}`}>{m.text}</div>):<div className="empty-small">告诉我你的灵感、卡点或想检查的章节。</div>}{busy&&<div className="chat-bubble assistant">思考中…</div>}</div><div className="drawer-compose"><select value={providerId} onChange={e=>setProviderId(e.target.value)}><option value="">{provider?modelLabel(provider,app.state.entities):'选择模型'}</option>{providers.map(p=><option key={p.id} value={p.id}>{modelLabel(p,app.state.entities)}</option>)}</select><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="询问助手，或描述你要执行的功能……" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}/><button className="button primary" disabled={busy} onClick={send}><Send size={16}/>发送</button></div></DrawerShell>;
}
