import { useState } from 'react';
import { Download, Plus, Trash2, Upload } from 'lucide-react';
import { useApp } from './context';
import { listEntities, type Entity } from './store';
import { platform } from './platform';

const rules=[['系统规则','尊重用户的最终决策权；正文创作优先针对当前章节或片段，设定类可按需批量生成。'],['REVIEW','评审给出可执行建议和原文证据。'],['SETTINGS','设定填充须核对现有事实，补充而不覆盖。'],['WRITING','保留用户文风和人物声线，除非明确要求改变。']];
function downloadSkill(item:Entity){const data=`---\nname: ${item.title}\ndescription: ${String(item.meta.summary??'创作辅助技能')}\n---\n\n# ${item.title}\n\n${item.content}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/markdown;charset=utf-8'}));a.download=`${item.title.replace(/[\\/:*?"<>|]/g,'-')}/SKILL.md`.replace('/SKILL.md','.skill.md');a.click();URL.revokeObjectURL(a.href);}
export function MianbaoPanel(){
  const app=useApp();const [open,setOpen]=useState<Record<string,boolean>>({skills:true,rules:true,personal:true,learned:true,chats:false});const [selectedSkill,setSelectedSkill]=useState<string|null>(null);
  const skills=listEntities(app.state,{kind:'skill'});const loaded=skills.filter(s=>s.meta.loadedForMianbao);const current=skills.find(s=>s.id===selectedSkill);
  const memories=listEntities(app.state,{kind:'memory'}).filter(e=>!e.workId);
  const personal=memories.filter(e=>e.category==='personalRule');const learned=memories.filter(e=>e.category!=='personalRule');const chats=listEntities(app.state,{kind:'chat'}).filter(e=>e.category==='助手');
  const toggle=(key:string)=>setOpen(x=>({...x,[key]:!x[key]}));
  const addSkill=async()=>{const name=await app.ask('新技能名称');if(name){const s=app.add('skill',name,'',{meta:{loadedForMianbao:true}});setSelectedSkill(s.id);}};
  const importSkill=async()=>{try{const f=await platform().importText();if(f){const s=app.add('skill',f.name,f.text,{meta:{loadedForMianbao:true}});setSelectedSkill(s.id);}}catch(e){app.notify(String(e));}};
  return <><section className="paper-page"><div className="panel-heading"><div><h3>记忆与学习</h3><p>开启后，面宝可把你明确表达的长期偏好沉淀为记忆。</p></div><label className="switch-inline"><input type="checkbox" checked={app.state.preferences.memoryLearning!==false} onChange={e=>app.replaceState({...app.state,preferences:{...app.state.preferences,memoryLearning:e.target.checked}})}/>{app.state.preferences.memoryLearning!==false?'已开启':'已关闭'}</label></div></section>
    <section className="paper-page mianbao-section"><button className="accordion-head" onClick={()=>toggle('skills')}><strong>技能装载 <small>{loaded.length}</small></strong><span>为面宝装载专属技能</span></button>{open.skills&&<><div className="action-row"><button className="button" onClick={()=>app.navigate('/agents/skills')}>Skill 仓库</button><button className="button" onClick={importSkill}><Upload size={14}/>导入技能</button><button className="button" onClick={addSkill}><Plus size={14}/>新建技能</button></div><div className="skill-list">{loaded.map(skill=><article className="skill-row" key={skill.id}><div><strong>{skill.title}</strong><small>{String(skill.meta.summary??skill.category??'自定义技能')}</small></div><button className="button" onClick={()=>setSelectedSkill(skill.id)}>查看</button><button className="icon-button" title="导出 SKILL.md" onClick={()=>downloadSkill(skill)}><Download size={14}/></button><button className="button" onClick={()=>setSelectedSkill(skill.id)}>编辑</button><button className="icon-button danger" title="卸载技能" onClick={()=>app.update(skill.id,{meta:{...skill.meta,loadedForMianbao:false}})}><Trash2 size={14}/></button></article>)}</div></>}</section>
    <section className="paper-page mianbao-section"><button className="accordion-head" onClick={()=>toggle('rules')}><strong>规则与约束 <small>{rules.length}</small></strong><span>系统内置与场景级的行为准则</span></button>{open.rules&&rules.map(([name,content])=><div className="rule-row" key={name}><strong>{name}</strong><p>{content}</p></div>)}</section>
    <section className="paper-page mianbao-section"><button className="accordion-head" onClick={()=>toggle('personal')}><strong>用户个人规则 <small>{personal.length}</small></strong><span>你专属的写作要求与偏好</span></button>{open.personal&&<><button className="button" onClick={async()=>{const title=await app.ask('个人规则名称');if(title)app.add('memory',title,'',{category:'personalRule'});}}><Plus size={14}/>新建</button>{personal.map(m=><div className="model-card" key={m.id}><div className="card-top"><input value={m.title} onChange={e=>app.update(m.id,{title:e.target.value})}/><button className="icon-button danger" onClick={()=>app.trash(m.id)}><Trash2 size={14}/></button></div><textarea value={m.content} onChange={e=>app.update(m.id,{content:e.target.value})}/></div>)}{!personal.length&&<div className="empty-small">暂无个人规则</div>}</>}</section>
    <section className="paper-page mianbao-section"><button className="accordion-head" onClick={()=>toggle('learned')}><strong>已沉淀记忆 <small>{learned.length}</small></strong><span>从会话中整理的长期偏好</span></button>{open.learned&&<>{learned.map(m=><div className="model-card" key={m.id}><div className="card-top"><input value={m.title} onChange={e=>app.update(m.id,{title:e.target.value})}/><button className="icon-button danger" onClick={()=>app.trash(m.id)}><Trash2 size={14}/></button></div><textarea value={m.content} onChange={e=>app.update(m.id,{content:e.target.value})}/></div>)}{!learned.length&&<div className="empty-small">暂无记忆</div>}</>}</section>
    <section className="paper-page mianbao-section"><button className="accordion-head" onClick={()=>toggle('chats')}><strong>会话记录 <small>{chats.length}</small></strong><span>历史对话存档</span></button>{open.chats&&<>{chats.map(c=><article className="model-card" key={c.id}><div className="card-top"><strong>{c.title}</strong><button className="icon-button danger" onClick={()=>app.trash(c.id)}><Trash2 size={14}/></button></div><pre>{c.content}</pre><button className="button" onClick={()=>{const title=`面宝记忆：${c.title}`;app.add('memory',title,c.content.slice(0,1500),{category:'learned'});app.notify('已加入可编辑记忆');}}>沉淀为记忆</button></article>)}{!chats.length&&<div className="empty-small">暂无会话记录</div>}</>}</section>
    {current&&<div className="modal-backdrop" onClick={()=>setSelectedSkill(null)}><div className="modal-card prompt-modal" onClick={e=>e.stopPropagation()}><div className="panel-heading"><h3>技能：{current.title}</h3><button className="button" onClick={()=>setSelectedSkill(null)}>完成</button></div><label>名称<input value={current.title} onChange={e=>app.update(current.id,{title:e.target.value})}/></label><label>技能内容<textarea className="prompt-body-editor" value={current.content} onChange={e=>app.update(current.id,{content:e.target.value})}/></label><div className="action-row"><button className="button" onClick={()=>downloadSkill(current)}>导出 SKILL.md</button><button className="button danger" onClick={()=>{app.trash(current.id);setSelectedSkill(null);}}>移入垃圾箱</button></div></div></div>}
  </>;
}
