import { useState } from 'react';
import { Copy, Eye, Plus, Trash2 } from 'lucide-react';
import { useApp } from './context';
import { listEntities, type Entity } from './store';
import { promptVariables, renderPrompt } from './promptPresets';

const categories=['全部','创作辅助','评审检查','分析工具','自定义'];
export function PromptTemplatesPanel(){
  const app=useApp();const [category,setCategory]=useState('全部');const [modal,setModal]=useState<{kind:'preview'|'edit';id:string}|null>(null);
  const [values,setValues]=useState<Record<string,string>>({});
  const [newVariable,setNewVariable]=useState('');
  const priority=['preset:prompt:female-long','preset:prompt:male-long','preset:prompt:murder-emotion','preset:prompt:murder-mechanism','preset:prompt:murder-deduction'];
  const prompts=listEntities(app.state,{kind:'prompt'}).sort((a,b)=>{const pa=priority.indexOf(a.id),pb=priority.indexOf(b.id);return (pa<0?99:pa)-(pb<0?99:pb);});
  const current=prompts.find(p=>p.id===modal?.id);
  const vars=current?promptVariables(current.content):[];
  const create=()=>{const entry=app.add('prompt','新建模板','',{category:category==='全部'?'自定义':category,meta:{systemPrompt:'',builtIn:false}});setModal({kind:'edit',id:entry.id});};
  const copy=(p:Entity)=>{const entry=app.add('prompt',`${p.title}（副本）`,p.content,{category:p.category,meta:{...p.meta,builtIn:false}});setModal({kind:'edit',id:entry.id});};
  return <><div className="section-actions"><div><h3>Prompt 模板</h3><p>分类管理、预览变量渲染、编辑、复制或移入垃圾箱。</p></div><button className="button primary" onClick={create}><Plus size={15}/>新建模板</button></div><div className="category-tabs">{categories.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}>{c} <small>{c==='全部'?prompts.length:prompts.filter(p=>p.category===c).length}</small></button>)}</div><div className="prompt-grid">{prompts.filter(p=>category==='全部'||p.category===category).map(p=><article className="prompt-card" key={p.id}><h3>{p.title}</h3><span className="tiny-label">{p.category}</span><p>{String(p.meta.systemPrompt??'')}</p><div className="prompt-variable-tags">{promptVariables(p.content).slice(0,4).map(v=><code key={v}>{`{${v}}`}</code>)}{promptVariables(p.content).length>4&&<small>+{promptVariables(p.content).length-4}</small>}</div><div className="action-row"><button className="button" onClick={()=>{setValues({});setModal({kind:'preview',id:p.id});}}><Eye size={14}/>预览</button><button className="button" onClick={()=>setModal({kind:'edit',id:p.id})}>编辑</button><button className="icon-button" title="复制模板" onClick={()=>copy(p)}><Copy size={15}/></button><button className="icon-button danger" title="移入垃圾箱" onClick={()=>app.trash(p.id)}><Trash2 size={15}/></button></div></article>)}</div>
  {current&&modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="modal-card prompt-modal" onClick={e=>e.stopPropagation()}><div className="panel-heading"><h3>{modal.kind==='preview'?`模板预览：${current.title}`:'编辑模板'}</h3><button className="button" onClick={()=>setModal(null)}>关闭</button></div>{modal.kind==='preview'?<><h4>System Prompt</h4><pre>{String(current.meta.systemPrompt??'')}</pre><h4>变量测试</h4><div className="form-grid">{vars.map(v=><label key={v}>{`{${v}}`}<input value={values[v]??''} onChange={e=>setValues(x=>({...x,[v]:e.target.value}))} placeholder={`输入 ${v} 的测试值`}/></label>)}</div><h4>渲染结果</h4><pre>{renderPrompt(current.content,values)}</pre></>:<><label>模板名称<input value={current.title} onChange={e=>app.update(current.id,{title:e.target.value})}/></label><label>分类<select value={current.category??'自定义'} onChange={e=>app.update(current.id,{category:e.target.value})}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>System Prompt（角色设定）<textarea value={String(current.meta.systemPrompt??'')} onChange={e=>app.update(current.id,{meta:{...current.meta,systemPrompt:e.target.value}})}/></label><label>User Prompt 模板（使用 {'{变量名}'} 占位）<textarea className="prompt-body-editor" value={current.content} onChange={e=>app.update(current.id,{content:e.target.value})}/></label><h4>变量</h4><div className="prompt-variable-tags">{vars.map(v=><code key={v}>{`{${v}}`} <button title={`删除变量 ${v}`} onClick={()=>app.update(current.id,{content:current.content.split(`{${v}}`).join('')})}>×</button></code>)}</div><div className="action-row"><input aria-label="新变量名" value={newVariable} onChange={e=>setNewVariable(e.target.value)} placeholder="新变量名，例如 chapter_content"/><button className="button" onClick={()=>{const name=newVariable.trim().replace(/[^A-Za-z0-9_]/g,'');if(!name)return;app.update(current.id,{content:`${current.content}\n{${name}}`});setNewVariable('');}}>添加变量</button></div><p className="muted">变量随模板自动提取；在预览中可逐项测试。</p><button className="button primary" onClick={()=>setModal(null)}>保存</button></>}</div></div>}</>;
}
